"""Core package for Google Ads budget alert system."""

from .config import (
    ApplicationConfig,
    ConfigError,
    SlackConfig,
    load_config,
    load_config_from_env_file,
    load_env_file,
    load_google_ads_config,
    load_schedule_config,
    load_slack_config,
)
from .forecast import (
    DailyForecastInput,
    DailyForecastResult,
    CombinedForecastInput,
    CombinedForecastResult,
    MonthlyPaceInput,
    MonthlyPaceResult,
    calculate_daily_projection,
    calculate_monthly_pace,
    build_combined_forecast,
)
from .google_ads_client import (
    DailyCostSummary,
    GoogleAdsClientConfig,
    GoogleAdsCostService,
    GoogleAdsCredentials,
    GoogleAdsSearchTransport,
    MonthToDateCostSummary,
    QueryRange,
    build_cost_query,
    build_daily_query_range,
    build_month_to_date_query_range,
)
from .schedule import (
    DailyScheduleConfig,
    DailyScheduleWindow,
    find_next_run_datetime,
    generate_daily_schedule,
    generate_upcoming_run_windows,
    generate_upcoming_run_times,
)
from .notification import SlackNotificationOptions, build_slack_notification_payload
from .workflow import (
    ForecastSnapshot,
    NotificationSender,
    SlackPayload,
    build_forecast_snapshot,
    dispatch_slack_alert,
)
from .logging_utils import LoggingConfig, configure_logging, get_logger
from .transports import DemoTransport
from .cli import (
    DoctorCheck,
    DoctorReport,
    SchedulePreview,
    SchedulePreviewWindow,
    build_argument_parser,
    main as cli_main,
    render_report,
    render_schedule_preview,
    run_doctor,
    run_schedule_preview,
    RunResult,
    RunError,
    render_run_result,
    run_once,
    generate_schedule_preview,
)

__all__ = [
    "ApplicationConfig",
    "ConfigError",
    "SlackConfig",
    "load_config",
    "load_config_from_env_file",
    "load_env_file",
    "load_google_ads_config",
    "load_schedule_config",
    "load_slack_config",
    "DailyForecastInput",
    "DailyForecastResult",
    "CombinedForecastInput",
    "CombinedForecastResult",
    "MonthlyPaceInput",
    "MonthlyPaceResult",
    "calculate_daily_projection",
    "calculate_monthly_pace",
    "build_combined_forecast",
    "DailyCostSummary",
    "GoogleAdsClientConfig",
    "GoogleAdsCostService",
    "GoogleAdsCredentials",
    "GoogleAdsSearchTransport",
    "MonthToDateCostSummary",
    "QueryRange",
    "build_cost_query",
    "build_daily_query_range",
    "build_month_to_date_query_range",
    "DailyScheduleConfig",
    "DailyScheduleWindow",
    "find_next_run_datetime",
    "generate_daily_schedule",
    "generate_upcoming_run_windows",
    "generate_upcoming_run_times",
    "SlackNotificationOptions",
    "build_slack_notification_payload",
    "ForecastSnapshot",
    "NotificationSender",
    "SlackPayload",
    "build_forecast_snapshot",
    "dispatch_slack_alert",
    "LoggingConfig",
    "configure_logging",
    "get_logger",
    "DemoTransport",
    "DoctorCheck",
    "DoctorReport",
    "SchedulePreview",
    "SchedulePreviewWindow",
    "build_argument_parser",
    "cli_main",
    "render_report",
    "render_schedule_preview",
    "run_doctor",
    "run_schedule_preview",
    "RunResult",
    "RunError",
    "render_run_result",
    "run_once",
    "generate_schedule_preview",
]
